[versions]
spring-boot    = "3.5.8"
lombok         = "1.18.42"
testcontainers = "1.21.3"
postgresql     = "42.7.8"

[libraries]
# Spring Boot BOM as a normal library alias (used with platform())
spring-boot-bom              = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

spring-boot-starter          = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web      = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jdbc= { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-kafka                 = { module = "org.springframework.kafka:spring-kafka" }

spring-boot-starter-test     = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-kafka-test            = { module = "org.springframework.kafka:spring-kafka-test" }

lombok                       = { module = "org.projectlombok:lombok", version.ref = "lombok" }
postgresql                   = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core                  = { module = "org.flywaydb:flyway-core" }
testcontainers-junit         = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-core          = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-kafka         = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
testcontainers-postgresql    = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]
spring-impl = [
    "spring-boot-starter",
    "spring-boot-starter-web",
    "spring-boot-starter-actuator",
    "spring-boot-starter-data-jdbc",
    "spring-kafka"
]

spring-test = [
    "spring-boot-starter-test",
    "spring-kafka-test",
    "testcontainers-junit",
    "testcontainers-core",
    "testcontainers-kafka",
    "testcontainers-postgresql"
]
